# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43a2dc52b472be35de1db527563f791586af9bc7828a96e9dfde2575d1dbb8deec49e0bd9421afc8aa275a7f7a1db8de33b2a109c262deb49662aef95e7d850d

test:
  secret_key_base: 5010408b7cf1e65f8ea8bced46f348d83b5e9bd5b1b9a8539a9398179d58aaa5e009336ff7845fae27dd8779bc905ddde6ec2f336fef08708d9b9f03306b76a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
